
package cs151_rps.io;

import java.util.Locale;

/* ************************** IMPORTANT **********************************
 * When mainGameFrame's main method is invoked, the first form               *
 * that displays is the startForm. When Start Game button is clicked     *
 * in the startForm, that is when mainGameFrame is displayed.                *
 * ***********************************************************************/

public class mainGameFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainGameFrame
     */
    public mainGameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpButton = new javax.swing.JButton();
        rockButton2 = new javax.swing.JButton();
        rockButton1 = new javax.swing.JButton();
        rockButton = new javax.swing.JButton();
        computerMoveLabel = new javax.swing.JLabel();
        playerMoveLabel = new javax.swing.JLabel();
        p1WinsLabel = new javax.swing.JLabel();
        tiesLabel = new javax.swing.JLabel();
        p1WinsTtlLabel3 = new javax.swing.JLabel();
        p2WinsTtlLabel = new javax.swing.JLabel();
        tiesTtlLabel = new javax.swing.JLabel();
        p1WinsTtlLabel = new javax.swing.JLabel();
        playerTitleLabel = new javax.swing.JLabel();
        currentRoundLabel = new javax.swing.JLabel();
        ofLabel = new javax.swing.JLabel();
        totalRoundLabel = new javax.swing.JLabel();
        computerTitleLabel = new javax.swing.JLabel();
        roundLabel = new javax.swing.JLabel();
        youWinLabel = new javax.swing.JLabel();
        computerWinsLabel = new javax.swing.JLabel();
        computerPredictionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        rockButton2.setText("Scissors");
        rockButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockButton2ActionPerformed(evt);
            }
        });

        rockButton1.setText("Paper");
        rockButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockButton1ActionPerformed(evt);
            }
        });

        rockButton.setText("Rock");
        rockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockButtonActionPerformed(evt);
            }
        });

        computerMoveLabel.setText("jLabel1");
        computerMoveLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));

        playerMoveLabel.setText("jLabel1");
        playerMoveLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));

        p1WinsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p1WinsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1WinsLabel.setText("# of Wins");
        p1WinsLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tiesLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tiesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiesLabel.setText("Ties");
        tiesLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        p1WinsTtlLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p1WinsTtlLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1WinsTtlLabel3.setText("# of Wins");
        p1WinsTtlLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        p2WinsTtlLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p2WinsTtlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p2WinsTtlLabel.setText("Wins");

        tiesTtlLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tiesTtlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiesTtlLabel.setText("Ties");

        p1WinsTtlLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p1WinsTtlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1WinsTtlLabel.setText("Wins");

        playerTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        playerTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerTitleLabel.setText("You");
        playerTitleLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        currentRoundLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        currentRoundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentRoundLabel.setText("1");

        ofLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ofLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ofLabel.setText("of");

        totalRoundLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalRoundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalRoundLabel.setText("n");

        computerTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        computerTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        computerTitleLabel.setText("Computer");
        computerTitleLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        roundLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        roundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundLabel.setText("Round");

        youWinLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        youWinLabel.setForeground(new java.awt.Color(0, 0, 153));
        youWinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        youWinLabel.setText("You win!");

        computerWinsLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        computerWinsLabel.setForeground(new java.awt.Color(255, 0, 0));
        computerWinsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        computerWinsLabel.setText("Computer wins!");

        computerPredictionLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        computerPredictionLabel.setForeground(new java.awt.Color(0, 102, 0));
        computerPredictionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        computerPredictionLabel.setText("Computer predicted . . . ");
        computerPredictionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(p1WinsTtlLabel))
                            .addComponent(p1WinsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p1WinsTtlLabel3)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(playerMoveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(youWinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rockButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rockButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(playerTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85)
                                        .addComponent(ofLabel))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tiesLabel)
                                        .addComponent(tiesTtlLabel)))
                                .addGap(18, 18, 18)
                                .addComponent(totalRoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(computerTitleLabel)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(computerMoveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(computerWinsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(currentRoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(p2WinsTtlLabel)
                        .addGap(78, 78, 78))))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(roundLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(computerPredictionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(roundLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(computerTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(playerTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ofLabel)
                        .addComponent(currentRoundLabel)
                        .addComponent(totalRoundLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p1WinsTtlLabel)
                        .addComponent(p2WinsTtlLabel))
                    .addComponent(tiesTtlLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p1WinsLabel)
                        .addComponent(p1WinsTtlLabel3))
                    .addComponent(tiesLabel))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(rockButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rockButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rockButton2)
                        .addGap(18, 18, 18)
                        .addComponent(helpButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerMoveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(youWinLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(computerMoveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(computerWinsLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(computerPredictionLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpButtonActionPerformed

    private void rockButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rockButton2ActionPerformed

    private void rockButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rockButton1ActionPerformed

    private void rockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rockButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                /* First, the startForm is opened. The mainGameFrame is displayed 
                 * when Start Game button is clicked in the startForm */
                new startForm().runStartForm();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel computerMoveLabel;
    private javax.swing.JLabel computerPredictionLabel;
    private javax.swing.JLabel computerTitleLabel;
    private javax.swing.JLabel computerWinsLabel;
    private javax.swing.JLabel currentRoundLabel;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel ofLabel;
    private javax.swing.JLabel p1WinsLabel;
    private javax.swing.JLabel p1WinsTtlLabel;
    private javax.swing.JLabel p1WinsTtlLabel3;
    private javax.swing.JLabel p2WinsTtlLabel;
    private javax.swing.JLabel playerMoveLabel;
    private javax.swing.JLabel playerTitleLabel;
    private javax.swing.JButton rockButton;
    private javax.swing.JButton rockButton1;
    private javax.swing.JButton rockButton2;
    private javax.swing.JLabel roundLabel;
    private javax.swing.JLabel tiesLabel;
    private javax.swing.JLabel tiesTtlLabel;
    private javax.swing.JLabel totalRoundLabel;
    private javax.swing.JLabel youWinLabel;
    // End of variables declaration//GEN-END:variables
}
