


package cs151_rps.io;

import cs151_rps.PassiveGameController;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/* ************************** IMPORTANT **********************************
 * This form is displayed when the mainGameFrame is started.                 *
 * When Start Game button is clicked, this form is closed and the        *
 * mainGameFrame is displayed.                                               *
 * ***********************************************************************/


public class startForm extends javax.swing.JFrame {

    /**
     * Creates new form startForm
     */
    public startForm() {
        initComponents();
    }

    //create the PassiveGameController reference to pass human player's info
    private PassiveGameController passiveController; 
    
    //create Message class reference to retreive messages
    Message message; 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundTtlLabel = new javax.swing.JLabel();
        numofRoundsTextField = new javax.swing.JTextField();
        gameTypeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gameTypeList = new javax.swing.JList();
        startGameButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });

        roundTtlLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        roundTtlLabel.setText("Number of Rounds: ");

        numofRoundsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numofRoundsTextFieldActionPerformed(evt);
            }
        });

        gameTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gameTypeLabel.setText("Game Type: ");

        gameTypeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Smart", "Random" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        gameTypeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        gameTypeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                gameTypeListValueChanged(evt);
            }
        });
        gameTypeList.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                gameTypeListComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(gameTypeList);

        startGameButton.setText("Start Game");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        warningLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        warningLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(startGameButton)
                .addGap(49, 49, 49)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(gameTypeLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(roundTtlLabel)
                .addGap(18, 18, 18)
                .addComponent(numofRoundsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numofRoundsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundTtlLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameTypeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startGameButton)
                    .addComponent(helpButton))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numofRoundsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numofRoundsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numofRoundsTextFieldActionPerformed

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        // TODO add your handling code here:
        /* if the number of rounds are entered and the gameType is chosen, 
         * display the mainGameFrame and close this form.
         * else, display and error message and go back to the startForm. 
         */
        String input = numofRoundsTextField.getText(); 
        
        //if the user didn't choose gameType, set it to Random
            if (gameTypeList.getSelectedIndex() == -1)
                gameTypeList.setSelectedIndex(0);
            String gameType = (String)(gameTypeList.getSelectedValue()); 
            
        try {
            int rounds = Integer.parseInt(input);
            
            //pass the info to PassiveGameController
            passiveController.setNumberOfRounds(rounds); 
            passiveController.setGameType(gameType); 
            
            //display the mainGameFrame and close this form 
            new mainGameFrame().setVisible(true);
            this.dispose();
        }
        catch (NumberFormatException nn){
            warningLabel.setText("Enter valid number of rounds and "
                    + " choose game Type."); 
        }
    }//GEN-LAST:event_startGameButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpButtonActionPerformed

    private void gameTypeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_gameTypeListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_gameTypeListValueChanged

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1PropertyChange

    private void gameTypeListComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_gameTypeListComponentShown
        // TODO add your handling code here:
        gameTypeList.setSelectedIndex(0);
    }//GEN-LAST:event_gameTypeListComponentShown

    //This method is called by mainGameFrame to run this form
    public void runStartForm() {
       //This is string array is created because the main methods requires 
        //a string array of arguments to run the the program
       String args[] = {""}; 
       this.main(args);
    }
    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new startForm().setVisible(true);
            }
        });
    } //end main 

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameTypeLabel;
    private javax.swing.JList gameTypeList;
    private javax.swing.JButton helpButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField numofRoundsTextField;
    private javax.swing.JLabel roundTtlLabel;
    private javax.swing.JButton startGameButton;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
