/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sohi_x2
 */
public class roundsPanel extends javax.swing.JPanel {

    /**
     * Creates new form roundsPanel
     */
    public roundsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundLabel = new javax.swing.JLabel();
        currentRoundLabel = new javax.swing.JLabel();
        ofLabel = new javax.swing.JLabel();
        totalRoundLabel = new javax.swing.JLabel();

        roundLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        roundLabel.setText("Round");

        currentRoundLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        currentRoundLabel.setText("1");

        ofLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ofLabel.setText("of");

        totalRoundLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalRoundLabel.setText("n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(roundLabel)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(currentRoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ofLabel)
                .addGap(18, 18, 18)
                .addComponent(totalRoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentRoundLabel)
                    .addComponent(ofLabel)
                    .addComponent(totalRoundLabel)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentRoundLabel;
    private javax.swing.JLabel ofLabel;
    private javax.swing.JLabel roundLabel;
    private javax.swing.JLabel totalRoundLabel;
    // End of variables declaration//GEN-END:variables
}
